### ISSUE TITLE
Composite id is incorrectly expanded in SQL

### ISSUE THREAD

**Issue by user2291296** [nhibernate/nhibernate-core#1376]
We have a table with a composite primary key mapped, as shown below:

`mapping.CompositeId().KeyReference(e => e.Node).KeyProperty(e => e.DtFr).UnsavedValue("any");`

We need to delete several rows from the table satisfying `n.Node.Contract.Code = "1234"` condition. We  use next HQL:

`delete from Entity n where n in (select c from Entity c where c.Node.Contract.Code = "1234")`

But in the generated SQL-query there are no parentheses around the primary key columns:

`select ... from ENTITY n where n.IDNODE, n.DTFR in (select c.IDNODE, c.DTFR ...`

We expect that n.IDNODE, n.DTFR columns should be surrounded with parentheses:

`select ... from ENTITY n where (n.IDNODE, n.DTFR) in (select c.IDNODE, c.DTFR ...`

Version of NHibernate is 4.1.1.4000.

**Comment by fredericDelaporte** [comment]
This looks to me as a database specific feature. Are multi-columns `in` clauses in SQL standard? You should likely use instead an `exists` clause, maybe like:

```sql
delete from Entity n where exists (from Entity c where c.Node.Contract.Code = "1234" and c = n)
```

**Comment by user2291296** [comment]
Good question about standard! I don't know the answer, though both Oracle 10g and Postgresql 9.6 support "in" clause with multiple columns.

As for "exists" then another problem appears (missing column aliases in SQL before IDNODE and DTFR):
`select ... from ENTITY n where exists (select c.IDNODE, c.DTFR from ... and (IDNODE = IDNODE and DTFR=DTFR)`.

**Comment by fredericDelaporte** [comment]
It appears the NHibernate `Dialect` base class has a `SupportsRowValueConstructorSyntaxInInList` which could be about that (or maybe not, since the case here needs a multi-column subquery in the in clause, while this property is documented to be about literal multi-columns in clauses). But it has no usage currently. This is maybe something coming from Hibernate, and so maybe there is some use of it to be ported from Hibernate, which could enable support of this feature.

To be checked by anyone who would be interested in having that feature.

**Comment by bahusoid** [comment]
This is actually already supported in hql if property is specified (special "id" name can be used `n.id in ...`):
```sql
delete from Entity n where n.id in (select c.id from Entity c where c.Node.Contract.Code = "1234")
```

And entity referencing was broken with d678c11bd5a488fb429223264499c44c810c3e16
