### ISSUE TITLE
SecondLevelCache CreateSQLQuery().UniqueResult<int>() throws Exception Specified cast is not valid.

### ISSUE THREAD

**Issue by joesun99** [nhibernate/nhibernate-core#1385]
Hi

Please check if this is a bug i get `Exception: System.InvalidCastException : Specified cast is not valid`.

For test case these two flags must be enabled:
```
 cache.use_second_level_cache=true 
 cache.use_query_cache=true 
```

TestCase:

```c#
[Test]
public void QueryCacheWithScalarFunctionThatReturnsInt()
{
	using (ISession s = OpenSession())
	{
		int result =  s
			.CreateSQLQuery("SELECT [dbo].[TestQueryCache] ()")
			.SetCacheable(true)
			.UniqueResult<int>();

		Assert.IsNotNull(result);
	}
}
```

Mssql scalar function create:

```sql
USE [nhibernate]
GO

/****** Object:  UserDefinedFunction [dbo].[TestQueryCache]    Script Date: 17.10.2017 14:11:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date, ,>
-- Description:	<Description, ,>
-- =============================================
CREATE FUNCTION [dbo].[TestQueryCache] 
()
RETURNS INT
AS
BEGIN
	
	RETURN DATEPART(YEAR, GETUTCDATE()) * 100 + DATEPART(MONTH, GETUTCDATE());

END

GO
```

**Comment by jaxx** [comment]
I've got exactly the same problem.

**Comment by hazzik** [comment]
Probably a `Regression`

**Comment by fredericDelaporte** [comment]
Still worth confirming: do you have this issue specifically with 5.0? It is written nowhere currently.

**Comment by jaxx** [comment]
I have NHibernate 5.0 now, but this bug was also in earlier versions. 4.1.1 for example.

**Comment by jaxx** [comment]
@hazzik Wow, that you left this one out from the 5.0.1 release. I've been waiting this issue to be resolved for 2-3 years for now. So we can't upgrade NH in our project and continue to use 3.3.5.4000.

**Comment by fredericDelaporte** [comment]
5.0.1 main purpose is to fix 5.0.0 regressions. This trouble is not a recent regression, and its PR (#1421) is not yet ready. One month after the major release, it is reasonable to have that release own regressions fixed, without waiting more for including unrelated bugs in the fix.

**Comment by jaxx** [comment]
So when I can expect this issue to be in release? In 6 months?

**Comment by gliljas** [comment]
You are more than welcome to help out with #1421

**Comment by fredericDelaporte** [comment]
I think this issue is in a dead-end. It is indeed written from the very beginning of `CustomLoader`: 
> ```c#
> // Currently *not* cachable if autodiscover types is in effect (e.g. "select * ...")
> ```

This is still the case on Hibernate side too.

A SQL scalar query use the "auto discover types" feature, which consists in determining the types of each column of the result set from the result set itself, instead of determining them from the query. This feature is not compatible with caching, because the cache needs to know the expected result types for re-assembling the cached results.

The proposed PR test case is only testing the "put in cache" case, and is not checking that retrieving from cache works. It does not, for a good reason.
Moreover for achieving "putting in cache", it has somewhat removed a part of the disassembling logic made for supporting a wide range of caches: so it succeeds within the NHibernate test base which only use a simple hashtable as a cache, but it may well causes serious issues for caching with real caches, especially with distributed ones.

**Comment by fredericDelaporte** [comment]
Still I have put some effort in checking why this issue exists, and so I was not that far away from a hacky work-around. I am not sure it is worth merging such a thing. In any case it should be completed with more tests, especially with cacheable of NH-1612 (due to a hack for it in the non cached path which I have not ported to the cached path) and NH-3666 tests. (NH-3666 is already about cacheable, but does not test retrieving from cache.)
