### ISSUE TITLE
Configuration.GenerateSchemaCreationScript() Exception with Oracle8iDialect and above

### ISSUE THREAD

**Issue by greenlight2k** [nhibernate/nhibernate-core#1438]
Issue since NH5:

When I use:
```c#
NHibernate.Cfg.Configuration.GenerateSchemaCreationScript(new Oracle8iDialect());
```
an exception is thrown:

```
Message:
Dialect does not support DbType.String
Parametername: typecode

StackTrace:
at NHibernate.Dialect.TypeNames.Get(DbType typecode)
at NHibernate.Dialect.Dialect.GetTypeName(SqlType sqlType)
at NHibernate.Mapping.Column.GetDialectTypeName(Dialect dialect, IMapping mapping)
at NHibernate.Mapping.Column.GetSqlType(Dialect dialect, IMapping mapping)
at NHibernate.Mapping.Table.SqlCreateString(Dialect dialect, IMapping p, String defaultCatalog, String defaultSchema)
at NHibernate.Cfg.Configuration.GenerateSchemaCreationScript(Dialect dialect)
```

I checked the sourcecode and found the problem:
Inside the constructor of `Oracle8iDialect` there was a line removed:
`RegisterCharacterTypeMappings();` (line 84)

I inherited a new class from `Oracle8iDialect` and added that line in the constructor.
This should fix the issue. But it needs to be confirmed and checked further.

Question is: Why was that mapping removed?

```csharp
public sealed class Oracle10gFixed : Oracle10gDialect
{
    public Oracle10gFixed()
    {
        RegisterCharacterTypeMappings();
    }
}
```

UPDATE:

This issue does not occur with `SchemaUpdate` or `SchemaExport`,
only with the `GenerateSchemaCreationScript`  method in `Configuration`.

**Comment by fredericDelaporte** [comment]
`RegisterCharacterTypeMappings` has been moved to the configure method, because it now depends on configuration settings. So the actual bug is the use of an un-configured dialect.

For obtaining a configured dialect, better use `NHibernate.Dialect.Dialect.GetDialect(cfg.Properties)` rather than a direct call to its constructor. (Assuming that `cfg` is a `Configuration` object and that the dialect to use has been specified in the configuration.)

Otherwise call the `Configure` method on the dialect before using it.

The fact that dialects need to be configured before being used is a breaking change from 5.0.0 that we have forgotten to document.

**Comment by hazzik** [comment]
Closing as not an issue.
