### ISSUE TITLE
Results are multiple with the same id

### ISSUE THREAD

**Issue by csharpdeveloper12** [nhibernate/nhibernate-core#1570]
Hi :),

i have a strange behavior with `ISet<>` and `FetchMode`.

Entity:
```
public class T1
{
public virtual System.Guid Id {get; set; }
public virtual System.Collections.Generic.ISet<T2> Items { get; set; }
}
```

Mapping1:
```
public class T1
{
...
base.Set(x => x.Items,
y =>
{
y.Cascade(NHibernate.Mapping.ByCode.Cascade.All);
y.Fetch(NHibernate.Mapping.ByCode.CollectionFetchMode.Join);
y.Lazy(NHibernate.Mapping.ByCode.CollectionLazy.NoLazy);
},
z => { ... }
);
}
```

Mapping2:
```
public class T1
{
...
base.Set(x => x.Items,
y =>
{
y.Cascade(NHibernate.Mapping.ByCode.Cascade.All);
y.Fetch(NHibernate.Mapping.ByCode.CollectionFetchMode.Subselect);
y.Lazy(NHibernate.Mapping.ByCode.CollectionLazy.NoLazy);
},
z => { ... }
);
}
```

Now i persist 1 T1 with 3 T2 items.

`var items = session.QueryOve<T1>().List();`
- If i execute `QueryOver<T1>` with Mapping2 everthing is ok.
items hast 1 item with 3 nested items (T2)
- But if i execute `QueryOver<T1>` with Mapping1 the behavior is:
items has 3 items (with the same id) and each item has 3 nested items (T2)

Is this an bug or correct if i use FetchMode.Join and the failure is by me and i forgot something in the mapping?

**Comment by bahusoid** [comment]
Looks like expected behavior. You can see the same behavior if you join/fetch lazy collection directly in query.

And unfortunately you can't fix it in the mapping - if you need to have FetchMode.Join for collection in mapping you need to remember to add distinct transformer to all your queries 
`session.QueryOver<T1>().Using(Transformers.DistinctRootEntity).List();`

**Comment by oskarb** [comment]
Please direct usage questions to the nhusers group.
