### ISSUE TITLE
Execute native select query that only return a single column cause exception if List<object[]>() is called

### ISSUE THREAD

**Issue by Doan-Van-Tuan** [nhibernate/nhibernate-core#1615]
I found a discrepancy in API. 
This code works fine:
`session.CreateSQLQuery("select Id, Name from MyTable").List<object[]>()`
But this code will throw an exception:
`session.CreateSQLQuery("select Name from MyTable").List<object[]>()`
If one wants to read data that way, one needs to use this code:
`session.CreateSQLQuery("select Name from MyTable").List<object>()`

I think API should be consistent, and the second code snippet should work normally.
I will create a test case when I found time for doing so.

**Comment by fredericDelaporte** [comment]
Changing this is likely to mean switching the single column case from yielding a list of a basic type element to a list of an array of object, with each array always containing a single element.

This would be a major breaking change for many cases and NHibernate APIs.

This behavior is also documented (maybe not very explicitly but still), see [The select clause](http://nhibernate.info/doc/nhibernate-reference/queryhql.html#queryhql-select) (HQL):

> Queries may return properties of any value type including properties of component type:
> ```sql
> select cat.Name from Eg.DomesticCat cat
> where cat.Name like 'fri%'
> 
> select cust.Name.FirstName from Customer as cust
> ```
> Queries may return multiple objects and/or properties as an array of type `object[]`
> ```sql
> select mother, offspr, mate.Name 
> from Eg.DomesticCat as mother
>     inner join mother.Mate as mate
>     left outer join mother.Kittens as offspr
> ```

Or [Projections](http://nhibernate.info/doc/nhibernate-reference/queryqueryover.html#queryqueryover-projections) (QueryOver):

> If a single property is projected, the return type can be specified using:
> ```c#
> IList<int> ages =
>     session.QueryOver<Cat>()
>         .Select(c => c.Age)
>         .List<int>();
> ```
> However, if multiple properties are projected, then the returned list will contain object arrays, as per a projection in ICriteria.

So in my point of view, this behavior is by design, documented, and should not be changed.

**Comment by Doan-Van-Tuan** [comment]
So I overlooked the documentation.
I still think API should be consistent. However, in any case, using an alias-to-bean transformer is a better approach. 
Thanks.

**Comment by fredericDelaporte** [comment]
I also disagree with considering this kind of consistency issue should be addressed. The general case treatment is ill suited for the single column case. There is not much value in bothering the users with un-boxing an atomic value out of a single element array each time they use a single column (or entity) query.

This current behavior may force users writing queries dynamic in regards to what they select to handle the single column/entity case specifically, but this use case is far for being the predominant use case, and that is not hard to handle. Especially when using a transformer, as you point out.

And also, this API works this way since the very beginning of NHibernate (I had to work on projects using beta versions prior to 1.0). But I do not remember having already seen this consistency concern being raised.

**Comment by Doan-Van-Tuan** [comment]
Actually my idea was we should support both, not just throw an exception like that.
My usecase is: the query is from an external file, and the system handles values programmatically. Then one day I got an exception because someone give the program a query that only returns one column. List<object[]>() is not working for such a query. If both List<object>() and List<object[]>() are supported then my code is much simpler.

In my view, this is still a bug. We need to support object[] in all case, and List<object>() should work as it is now. Throwing an exception is not nice and forcing user to treat single column query differently from all other queries.

**Comment by Doan-Van-Tuan** [comment]
However I have work-around and it's OK, so this is not a problem for me. That why I closed this issue.

**Comment by Doan-Van-Tuan** [comment]
@fredericDelaporte Do I need to re-open the issue so that you see my comment?

**Comment by fredericDelaporte** [comment]
No I see them. But I still mostly disagree.

At most maybe an improvement could be done, provided it has a very small impact, like checking the `List<T>` generic type argument just before yielding the result for boxing a single column result into a array if the generic type is `object[]`. But it should still go on supporting the direct typing without a boxing array, and go on defaulting to direct typing for non generic methods.

And such a thing would have to be done for all API (Criteria, HQL, QueryOver) and all similar strongly typed methods (`UniqueResult<T>`, ...).

Then we would have a discrepancy between generic vs non-generic, especially for those who would not know that the default is "direct typing" for single column/entity queries and would believe the APIs yields `object[]` in all cases.

Moreover, it would mean than single entity queries could then be also have they rows boxed as an object array, which looks like a strange thing.

In fact, the current behavior with single columns queries is very consistent with single entity queries. When we query for a list containing as rows only one entity per row, we do not expect to get each row back a an array of objects.
