### ISSUE TITLE
Case When ... Then ... End => NHibernate query problem

### ISSUE THREAD

**Issue by bilalcorbacioglu** [nhibernate/nhibernate-core#1648]
Hi everyone,

Probably, I found a bug. This sql query,

```sql
    ORDER BY 
    Priority DESC,
    CASE WHEN Priority<>0 THEN CreatedOn END DESC,
    SpecificRank ASC
```

And This nhibernate query,

```c#
criteria.AddOrder(new Order("Priority", false));
criteria.AddOrder(new Order(Projections.Conditional(Restrictions.Where<Campaign>((x) => x.Priority != 0), Projections.Constant(CampaignScheme.Properties.CreatedOn), Projections.Constant(CampaignScheme.Properties.Id)), false)); // Properties.Id parameter =>actually, i am not using else block, but this parameter required.
criteria.AddOrder(new Order("SpecificRank ", true));
```
but ones point, i dont understand

```c#
criteria.AddOrder(new Order(Projections.Conditional(..., ..., Projections.Constant(CampaignScheme.Properties.Id)), ...));
```

Else block not running or maybe, running 'else block' then running 'SpecificRank Order query', thus, before 'else block' crushed ? **( Why not crushed 'if block' ? )**

**Comment by fredericDelaporte** [comment]
I am unable to make sens of your report. If you really think there is a NHibernate bug, better submit [a failing test case](https://github.com/nhibernate/nhibernate-core/blob/master/CONTRIBUTING.md#creating-a-test-case-to-verify-the-issue). Otherwise please ask for support on a [NHUsers group](http://nhibernate.info/groups.html).

**Comment by fredericDelaporte** [comment]
I do not understand what do you mean by the use of the "crush" verb. You should also submit full queries (both expected SQL, obtained SQL if any and attempted criteria) instead of just fragments. And define what is "wrong working". There are many ways for things to go wrong. Tell what is happening precisely.

Of course if you supply a good test case, it should then explain all this.

**Comment by hazzik** [comment]
First of all, you have an error in your query. You use `Projection.Constant(...)` which would be translated as a parameter. You need to change these to `Projection.Property(...)`

Second, What I understand from your question (I'm here with @fredericDelaporte and also do not fully understand what you are trying to say):

1. You want to be able to write a case expression without else block and wondering why else is required.
2. Because you have used else block order of your query is not always match your expectation. 

Number one can be treated as a feature request. To solve the actual problem you are facing you need to use `Projections.Constant(null)` in the else block to get the results you want to get. 


This is the code you are looking for:

```csharp
criteria.AddOrder(new Order("Priority", false));
criteria.AddOrder(
	new Order(
		Projections.Conditional(
			Restrictions.Where<Campaign>(c => c.Priority != 0),
			Projections.Property<Campaign>(c => c.CreatedOn),
			Projections.Constant(null)),
		false));
criteria.AddOrder(new Order("SpecificRank ", true));
```

**Comment by hazzik** [comment]
@bilalcorbacioglu does my previous comment answer your question?
