### ISSUE TITLE
Looking for wrong version of Remotion.Linq.EagerFetching

### ISSUE THREAD

**Issue by JHotterbeekxBannerconnect** [nhibernate/nhibernate-core#1653]
Hi,

I've been struggling with this issue on and off for some days now, but can't seem to solve it. We are running on the latest version of nHibernate, together with fluent. The issue occurs when updating the dependency 'Remotion.Linq.EagerFetching' from version 2.1.0 to its latest version 2.2.0. As soon as we try and do a query after this update we get an exception at runtime, where it seems that is looking for version 2.1.0 inside of or next to version 2.2.0. See screenshot.

![image](https://user-images.githubusercontent.com/20039080/38600658-3878aa68-3d65-11e8-8dae-8dc8503bc201.png)

I really don't know where to look anymore. I've removed all the packages and reinstalled then, cleared cache, checked dll versions, look for references to 2.1.0, but nothing. Everything works when we use Remotion.Linq.EagerFetching 2.1.0, but fails when we update it to 2.2.0. I'm not sure this issue is part of nHibernate or Remotion.Linq. It seems to be thrown from NHibernate if I look at the stacktrace.

![image](https://user-images.githubusercontent.com/20039080/38600761-88ecc29a-3d65-11e8-96eb-62a9568d9a12.png)

Anybody got any idea how to solve this?

**Comment by fredericDelaporte** [comment]
Since this reference is upgraded to 2.2.0 in NHibernate 5.2.0 (#696, not yet released), I do not think anyone will take much time investigating the issue here, whether that is an NHibernate trouble or an external one (missing bindings redirect?). Better keep using 2.1.0 if possible. Upgrading to 2.2.0 requires some code changes in NHibernate anyway, which are done for 5.2.0.

**Comment by JHotterbeekxBannerconnect** [comment]
Okay, thanks for the response. We'll leave it at 2.1.0 for now.
