### ISSUE TITLE
ASP.NET Core: Cannot set "nhibernate-logger" in app.config. There is no app.config in .Net Core applications

### ISSUE THREAD

**Issue by karelkral** [nhibernate/nhibernate-core#1697]
There is "nhibernate-logger" setting, which is read from app.config or web.config. 
But in .ASP.Net Core, app.config does not exist. There is appsettings.json only. Would it be possible to set nhibernate-logger from NHibernate.Cfg.Environment, from hibernate.cfg.xml or programmaticaly? 

There is workaround how to copy settings from appsettings.json to ConfigurationManager, but this is not clean solution [here](https://stackoverflow.com/questions/50258251/net-core-2-0-appsettings-with-net-full-framework-using-configurationmanager?noredirect=1&lq=1)

The code for reading nhibernate-logger is in NHibernateLogger

``` csharp
private static string GetNhibernateLoggerClass()
{
      var nhibernateLogger = ConfigurationManager.AppSettings.Keys.Cast<string>().FirstOrDefault(k => nhibernateLoggerConfKey.Equals(k, StringComparison.OrdinalIgnoreCase));
	string nhibernateLoggerClass = null;
	if (string.IsNullOrEmpty(nhibernateLogger))
	{
		// look for log4net.dll
               // other code...			
        }
	return nhibernateLoggerClass;
}
```

**Comment by fredericDelaporte** [comment]
Hello,

You have reached the NHibernate bug tracker. Please direct usage questions to the user groups:
http://nhibernate.info/groups.html

But instead of using the setting, you can set a logger programmatically: use `NHibernateLogger.SetLoggersFactory`. An example is available [here](https://github.com/nhibernate/nhibernate-core/blob/5.1.2/src/NHibernate.Example.Web/Infrastructure/AppSessionFactory.cs).
