### ISSUE TITLE
Incorrect number of children returned with FetchMany after an Insert during a transaction

### ISSUE THREAD

**Issue by DaEkstrim** [nhibernate/nhibernate-core#1810]
My environment:
FluentNhibernate: 2.1.2
NHibernate: 5.1.3
DotNet Core: 2.1.0
Datbase: SQL Server 2017
App Type: Console Application

I seem to have encountered an issue where when querying a session for an entity's children for the second time after adding a child to the database after the first query during a transaction, Nhibernate seems to be caching the children of the entity and returning the results of the first query. Even though the SQL Profiler is showing that the query hit the database, Nhibernate is returning the old (and incorrect) results.

```
using (var session = _nHibernateSessionProvider.GetNewSession())
{
	// Get the only parent in the database (prepopulated with 1 Parent and 1 Child)
	var Parent = session.Query<Entities.Parent>().SingleOrDefault();

	// Begin session trx
	var trx = session.BeginTransaction();

	// Count the number of children the parent has - Result: 1
	var parentChildCount1 = session.Query<Entities.Parent>().Where(u => u.Id == Parent.Id).FetchMany(u => u.Children).SingleOrDefault().Children.Count();

	// Add a new child to the parent
	session.Save(new Entities.Child { IsDeleted = false, Parent = Parent });

	// Count the number of children the parent has - Result: 1 [INCORRECT]
	var parentChildCount2 = session.Query<Entities.Parent>().Where(u => u.Id == Parent.Id).FetchMany(u => u.Children).SingleOrDefault().Children.Count();

	// Count the number of children who have the specified parent - Result: 2
	var directChildCount = session.Query<Entities.Child>().Where(uA => uA.Parent.Id == Parent.Id).ToList().Count;

	// Rollback trx for replayability
	trx.Rollback();
}
```

Is this working as intended? Should I be tackling this differently? I'm using quite a complex Unit Of Work through Castle interceptors which also takes care of creating and disposing a session, so while in the above example first query and second query are in the same code block, in reality, these could be miles apart from each other in completely different modules, just accessing the same data by chance.

I can provide you with a project which reproduces this error if you require it.

**Comment by DaEkstrim** [comment]
Clarification: Issue seems to happen even if no transaction is explicitly used.

**Comment by hazzik** [comment]
Need a flush after session.Save()

**Comment by DaEkstrim** [comment]
That was the first thing I tried to resolve the problem, however it is not the case.

Unrelated note: I'm updating the above example to use `.SingleOrDefault()` instead of `.Take(1).First()` as it is skewing the results of the FetchMany since it's appending `FETCH FIRST 1 ROWS ONLY` to the query and thus even if there's more than 1 child in the collection, it still picks up only one (since 1 row is being returned)

**Comment by fredericDelaporte** [comment]
For me, this is a user bug. It is the user responsibility to maintain loaded entities state integrity. When you save a new child, you should also explicitly add it in its parent collection, if its parent collection is already loaded. (You can check this with `NHibernateUtil.IsInitialized`, both on the parent itself (in case you load it as a proxy) and on the parent collection.)

NHibernate will not guess the collection has virtually been changed on the database side just by setting the child parent property.

The documented examples in NHibernate on bidirectional associations update the two ends for ensuring loaded entities state integrity, like in this example from [Parent/Child example](http://nhibernate.info/doc/nhibernate-reference/example-parentchild.html#example-parentchild-bidir):

> The following code would be used to add a new `Child`.
>```c#
>Parent p = session.Load<Parent>(pid);
>Child c = new Child();
>c.Parent = p;
>p.Children.Add(c);
>session.Save(c);
>session.Flush();
>```

**Comment by DaEkstrim** [comment]
If that was the case, why am I seeing  NHibernate hitting the database through the SQL Profiler? As far as the intent goes, the code is asking Nhibernate, as an ORM, to perform a query on the database, which for all intents and purposes, is actually hitting the database, but then the results are incorrect. Rather than this being a "user bug", if you insist, I'd classify this as "By design" or "Will not support", but in my opinion it is definitely not a "user bug". 

Separation of concern demands that the business logic does not perform operations in a way that conveys understanding of how the sub module operates. That would just be a concern leak. 

But thanks for your time in reading this issue.

**Comment by DaEkstrim** [comment]
Thank you for the detailed explanation. I had a rough idea through reading the debug log and Nhibernate source code but having you confirm it is very helpful.

With regards to `Refresh`, I also did try that approach using `.WithOptions(o => o.SetCacheMode(CacheMode.Refresh))` (in this case it would be on the second query for example). Since I'm using a Repository layer (whose concern is making sure that it abides by the NH's rules) I do have knowledge when the business logic intends to eager fetch the children of an entity, and thus I could easily set that option, however it didn't change the results. 

Since you said that the `Refresh` is set on the entity (Parent), could I convey intent to Nhibernate to refresh the child collection as well?

**Comment by fredericDelaporte** [comment]
> With regards to `Refresh`, I also did try that approach using `.WithOptions(o => o.SetCacheMode(CacheMode.Refresh))`

`SetCacheMode` is a second level cache feature (cache at the session factory level, which could even be distributed), which is not implied here. It has no effect on the first level cache (session cache).

I was meaning to do something like `ISession.Refresh(parent)`.

But, moreover the fact I have not check it would also refresh the collection, this is still not a correct way of handling that case in my opinion, because this forces a round-trip to database while really the child should just be explicitly added to the parent collection instead.
(If adding the child to the collection causes a double update issue, the mapping is likely missing `inverse="true"` on the collection. If you do not want to set an inverse side for being able to update the link on both sides, that is an unsupported use case, and you will have to cope with its consequences.)

**Comment by DaEkstrim** [comment]
Yes the inverse is set. I understand what you mean, and while I do agree with you from an ORM perspective, from a separation of concern point of view, the business logic should not need to concern itself about data consistency, as its intent is simply to add a new entity to the database which happens to be a child of another entity.

> because this forces a round-trip to database
The thing is, the round drop to the database is still happening even though the entity is in the first level cache, so no loss in actually using the data that's being loaded from the database rather than just discarding it.

Since this is an edge case where data just inserted is being queried again through an eager load instruction while in the same transaction, I'll be using the unit of work to monitor all entities added during the transaction, study the entities which are being eager loaded, and if there's a match, I'll manually instruct Nhibernate to clear the session before executing the query. Is it ideal? No. But I'd rather have truth, consistency and assurance while losing some performance.

I have thoroughly enjoyed our discussion and I deeply appreciate you taking time to answer my queries. Keep up the good work; I've been with you since NH 1.2 :)

**Comment by bahusoid** [comment]
> I'll be using the unit of work to monitor all entities added during the transaction, study the entities which are being eager loaded, and if there's a match, I'll manually instruct Nhibernate to clear the session before executing the query. 

Really? Modifying your "adding" code to 
```C#
var child = new Entities.Child { IsDeleted = false, Parent = Parent })
Parent.Children.Add(child);
```
looks like much more clean solution to me.

With cascade mapping you can also get rid of `session.Save` for each added entity. And do simply `session.Flush` in the end of your UOW. 
 
And I really don't understand your "concern leak". That's exactly the code you would write without DB involved.   On the contrary your expectation that it's going to be added magically to collection because child is saved to DB - looks like "concern leak" to me.

**Comment by DaEkstrim** [comment]
> On the contrary your expectation that child is going to be added magically to parent collection because child is saved to DB - looks like "concern leak" to me.

That only tells me that you probably either read half of the thread or didn't understand the issue. My issue was, that I'm performing a query to the database, and the results returned do not reflect what's in the database. The way this multi-tenant application is designed is completely event based using AOP interceptors with runtime compilation so the first query doesn't know that there maybe the second query, and the second query doesn't know that there maybe the first query.

And yes it is a concern leak, because why would I be adding `Parent.Child.Add(child)`? The reason is not in any way related to any business logic but it's to counter act the side effects of how a particular ORM operates. Thus adding that line is purely based on the knowledge of how the ORM operates. Also if some junior developer forgets to do it and the unit tests miss it, this silent (data) bug leaks out onto production. Definitely no-go.

Also my solution which you quoted was roughly explained. By monitor, I have a list of type names, and I have my own Prefetch instruction system wrapping around Nhibernate so getting access to the prefetching entities was a trivial task.

Thank you for your input though.

**Comment by fredericDelaporte** [comment]
> And yes it is a concern leak, because why would I be adding Parent.Child.Add(child)?

Because that is just the most consistent thing to do. The way this code is done create an inconsistency. Maybe some other ORM mechanisms may overcome it, but the inconsistency is still due to the user code, not to NHibernate. Anyone, beginner or not, should ensure he does not create code that does inconsistent changes in memory, instead of relying on the ORM for fixing the inconsistency.

Now, of course, you are free to do as you want with the code you are responsible for. But I disagree the issue described here should be considered as a NHibernate shortcoming, if your arguing is meant to imply this.

**Comment by DaEkstrim** [comment]
> should be considered as a NHibernate shortcoming, if your arguing is meant to imply this.

Absolutely not. The shortcoming was my understanding on how Nhibernate treats incoming data when the 1st-level cache of the same session provided by the UOW already contains said data. After almost 10 years, I'm still learning about NHibernate.

However, since I basically have my own micro-orm shell wrapped around Nhibernate (for the sake that if a particular tenant requires a different repository implementation, I would not need to implement anything apart from the repository layer), adding that line (or any ORM specific related code) in the business logic would (in my opinion) be risky.

**Comment by bahusoid** [comment]
I've read thread - I've just highlithed the part that I think is done wrong - child object saving. What if some code below after your `session.Save(child)` call checks `Parent.Child` collection instead of query? Do you also expect it to be updated by ORM? Well in NHibernate if collection is not yet initialized you are lucky, but if it's already initialized it's your responsibility to mantain its state (so basically the same issue you described).

IMHO concern leak is calling `session.Save(child)` (which as I already said can be avoided by mapping) and `Parent.Child.Add(child)` is actually what you are doing from business standpoint (as later you are checking it and expect it to have some data)
