### ISSUE TITLE
NullReferenceException after ToList

### ISSUE THREAD

**Issue by junalmeida** [nhibernate/nhibernate-core#1815]
After running this code: 

```C#
          var lista = query
                    .GroupBy(x => new
                    {
                        ItemConfiguracaoId = x.ItemConfiguracao.Id,
                        Status = x.Status
                    })
                    .Select(x => new
                    {
                        x.Key.ItemConfiguracaoId,
                        x.Key.Status,
                        Quantidade = x.Count(),
                        ChamadoMaisAntigo = x.Min(y => y.DataStatus),
                    }).ToList();
```
I got the following NullReferenceException with the following StackTrace. 

![image](https://user-images.githubusercontent.com/991675/43017760-bffd3780-8c2d-11e8-8144-f2c17e11db88.png)

Can you please help me? Let me know if I need to provide more details (such as current mapping-by-code classes and domain).

Version of nHibernate: 5.1.3

**Comment by junalmeida** [comment]
I just figure out how to overcome this issue: 

```C#

            var lista = query
                    .GroupBy(x => new
                    {
                        ItemConfiguracaoId = (long?)x.ItemConfiguracao.Id,
                        Status = x.Status
                    })
                    .Select(x => new
                    {
                        x.Key.ItemConfiguracaoId,
                        x.Key.Status,
                        Quantidade = x.Select(y => y.Id).Count(),
                        ChamadoMaisAntigo = x.Min(y => y.DataStatus),
                    }).ToList();

```
Look at `(long?)x.ItemConfiguracao.Id`. But NHibernate should definitely give a better exception than NullReferenceException.

**Comment by hazzik** [comment]
Lets run the experiment. Run the following code:

```csharp
          var lista = query
// vvv this is the only change to the original query
                    .ToList() 
// ^^^ this is the only change to the original query
                    .GroupBy(x => new
                    {
                        ItemConfiguracaoId = x.ItemConfiguracao.Id,
                        Status = x.Status
                    })
                    .Select(x => new
                    {
                        x.Key.ItemConfiguracaoId,
                        x.Key.Status,
                        Quantidade = x.Count(),
                        ChamadoMaisAntigo = x.Min(y => y.DataStatus),
                    }).ToList();
```

**Comment by junalmeida** [comment]
@hazzik Sorry for my delay, I am not getting notifications from GH. My query should not get all data from database. The grouping must be made on the database end. There is no point adding ```.ToList()``` before the ```.GroupBy```

**Comment by hazzik** [comment]
I didn’t ask what it should or should not do. I asked what you see when you do that. Please answer that question.

**Comment by junalmeida** [comment]
@hazzik omg, sorry then. I've done this already and it works.

**Comment by hazzik** [comment]
Ok thanks. That is strange. It should not work the same way as original query. Can you double check that you do not have cast `(long?)` in that query?

**Comment by fredericDelaporte** [comment]
The bottom line of this trouble is, linq-to-object would also yield a null reference exception with the foreseeable cause of this exception for linq-to-nhibernate.

The foreseeable cause of this exception is `x.ItemConfiguracao` being nullable, and sometimes `null`, causing the group by to normally fail in a null reference exception when used with linq-to-object.

With linq-to-nhibernate, the group by happening in SQL, and SQL being transitive with null (a bit like using `?.`), the SQL just yield a null instead of the value. But then, if the projection has to put it in a non-nullable value, a null reference exception occurs again, and this is not only normal but actually the root trouble, trying to use something null as a non-null value.

The casting to `long?` is just a hack exploiting SQL behavior with null, which would not work with linq-to-object. A better way to rewrite the query would be to account for `ItemConfiguracao` nullability, by using `x.ItemConfiguracao?.Id` instead. But unfortunately, expression trees do not support `?.`.

As in your case linq-to-object works, according to you, on your query case, either for some reason it has not be run on the same data set, or some other condition, that we cannot guess from the partial code submitted here, causes the trouble.

If it is the later, please provide a complete example allowing to reproduce the trouble. See [contributing](https://github.com/nhibernate/nhibernate-core/blob/5.1.3/CONTRIBUTING.md).
