### ISSUE TITLE
Casting types inside formula throws exception

### ISSUE THREAD

**Issue by mmalyska** [nhibernate/nhibernate-core#1832]
NH version: **5.0.3**

When we started using filters inside HBMs maps that contains formulas with postgresql type casting, NH started to throw exception:

> System.ArgumentException: 'Invalid filter-parameter name format; the name should be a property path.'

After some debugging I found value that throws:
filterParameterName hase value set to **:text**

Example formula that throws exception:

``formula="initcap(`IMIE`)::text || ' '::text || initcap(`NAZWISKO`)::text"``

**Comment by fredericDelaporte** [comment]
See [Types cast](https://www.postgresql.org/docs/10/static/sql-expressions.html#SQL-SYNTAX-TYPE-CASTS) in PostgreSQL documentation:

> A type cast specifies a conversion from one data type to another. PostgreSQL accepts two equivalent syntaxes for type casts:
>```sql
>CAST ( expression AS type )
>expression::type
>```
>The `CAST` syntax conforms to SQL; the syntax with `::` is historical PostgreSQL usage.

Better use the syntax which is conform to SQL standard.

I do not think NHibernate's parsing logic should try to accommodate every vendor specific syntax, especially when they have standard counterparts.

**Comment by mmalyska** [comment]
Now formula looks like that
``CAST(initcap(`IMIE`) AS TEXT) || CAST(' ' AS TEXT) || CAST(initcap(`NAZWISKO`) AS TEXT)``

it gets translated to 
`CAST(initcap(osobyfizyc0_."IMIE") AS osobyfizyc0_.TEXT) || CAST(' ' AS osobyfizyc0_.TEXT) || CAST(initcap(osobyfizyc0_."NAZWISKO") AS osobyfizyc0_.TEXT)`

The type gets translated to: `osobyfizyc0_.TEXT`, it should be `TEXT`

**Comment by fredericDelaporte** [comment]
This one happens because in the case of PostgreSQL, types names are not included in dialect keywords.

(This seems to date back to 0ad0ba1 (#654), see [here](https://github.com/nhibernate/nhibernate-core/commit/0ad0ba1293450844798f76a4332c6fce68bc417f#diff-3b016c27553f4659e9dead7ddd463e45R12). @ngbrown, do you remember why is this?)

You should be able to overcome this by adding `"text"` to the dialect keyword list. With the session factory, it can be done with `sessionFactory.Dialect.Keywords.Add("text")`.

**Comment by mmalyska** [comment]
@fredericDelaporte Thanks, that resolved my issue.
