### ISSUE TITLE
Apparently the first query on new session must be synchronous

### ISSUE THREAD

**Issue by mhjorth** [nhibernate/nhibernate-core#1834]
I've been trying to use the asynchronous methods in my project.
I have a session factory which creates a session on an Oracle database. My problem is that if the first query is asynchronous I get an error:
           
            using (var session = NhibernateConfiguration.CreateSessionFactoryCi().OpenSession())
            {
                var instrument = await session.GetAsync<Instrument>(InstrumentId);
            }

Oracle.ManagedDataAccess.Client.OracleException : ORA-12541: TNS: No listener
OracleInternal.Network.NetworkException : ORA-12541: TNS: No listener
System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it 10.16.70.49:1521
   at NHibernate.Loader.Loader.<LoadEntityAsync>d__23.MoveNext()

if I enter a synchronous dummy query first then it works:

           using (var session = NhibernateConfiguration.CreateSessionFactoryCi().OpenSession())
            {
                session.CreateSQLQuery("select 1 from dual").List();
                var instrument = await session.GetAsync<Instrument>(InstrumentId);
            }

Michael

**Comment by fredericDelaporte** [comment]
This looks as an external issue. Is there anything which let you think it is instead NHibernate fault?

We have a lot of tests with asynchronous calls being the first thing done after opening a session, without seeing this error. (And we do run those tests on Oracle, 12c with this [data access nuget package](https://www.nuget.org/packages/Oracle.ManagedDataAccess/12.1.2400).)

As a side note, as far as I know, Oracle managed data access does not actually implement async methods. This API does not override the async methods provided by `System.Data.Common.Db*` classes, which does fallback on synchronous methods.

**Comment by mhjorth** [comment]
The thing that made me think that NHibenate is the cause is that the only thing I changed was using the GetAsync method instead instead of Get.

**Comment by mhjorth** [comment]
Of course it is possible that the error is in another component as Oracle driver and FluentNHibernate is involved as well. I can reproduce the problem in a minimal application selecting from dual only. I'll have a look to see if I can create a test case.

**Comment by hazzik** [comment]
As per @fredericDelaporte

**Comment by mhjorth** [comment]
I've been investigating further and found the problem.
It happens when I add a dummy connection string to the driver and the real connection string in the ConnectionProvider. In this situation I am able to get the error. I am working on a test case.

**Comment by mhjorth** [comment]
Ok, I finally got it. 
What tricked me is the arbitraryness on which ConnectionProvider method that opens the connection. I now realize that I have to override both GetConnection methods to be sure that no matter if the first query is synchronous or asynchronous the session will get the right connection string. 
So I now know exactly how to make it fail and fortunately also how to avoid it.

**Comment by fredericDelaporte** [comment]
So to summarize it:

- The application is using a custom `IConnectionProvider`, deriving from, I guess, `DriverConnectionProvider` instead of `ConnectionProvider`.
- The application custom `IConnectionProvider` does override `GetConnection` but not `GetConnectionAsync`.
- The application is configured with an invalid connection string for the `ConnectionProvider`, but the `GetConnection` override does not use its `ConnectionString` property and instead use another connection string.
- The application use the default connection release mode `AfterTransaction` with a single transaction per opened session, or use the `OnClose` connection release mode.
  With `AfterTransaction`, a connection acquired in a transaction stays acquired and is reused for subsequent queries till the transaction is committed, or till the session is closed. With `OnClose`, it stays acquired and is reused for subsequent queries till the session is closed.

So in such a setup, it is normal that using the session succeed only if its first usage is synchronous. And as you have inferred, this is a bug in the application custom connection provider, which should override also `GetConnectionAsync`.

This trouble would have been avoided if instead of deriving from `DriverConnectionProvider` the application was deriving from `ConnectionProvider`. `GetConnectionAsync` is abstract and forgetting to override it would have lead to a compilation error.
(Note that `DriverConnectionProvider.CloseConnection` does furthermore dispose the connection, while `ConnectionProvider.CloseConnection` does not. If you need it to be disposed on close, deriving from `ConnectionProvider` then imply to also override `CloseConnection` for disposing it.)

**Comment by mhjorth** [comment]
Exactly. When working on an existing application where the database connection was configured years ago I fell into this trap.
