### ISSUE TITLE
one-to-one constrained fails if foreign type is a base type (Table per Hierarchy)

### ISSUE THREAD

**Issue by fubar-coder** [nhibernate/nhibernate-core#1841]
The returned type isn't a type derived from the given base type. Instead, it's the base type itself even though it's abstract (both as type and in the mapping).

The current workaround is to add a `lazy="false"`.

**Comment by fredericDelaporte** [comment]
What is the failure exactly? Is it that you were expecting to have something of the concrete class? Or does it fail to load, or fail to do whatever else?

The former is a wrong expectation, see below. It is the later, please provide a test case. The code base already have some `one-to-one` constrained mappings toward a base class, like [this](https://github.com/nhibernate/nhibernate-core/tree/5.1.3/src/NHibernate.Test/NHSpecificTest/NH1584). Granted, this one does not load that side, but adding a test doing so and accessing the constrained side properties does not cause any failure.

When mapping a `one-to-one` as constrained, it tells NHibernate that the other side forcibly exists, allowing it to be proxified for lazy-loading.

The entity proxy can only be derived from the mapped type, since it is not yet loaded. This is by design of the default lazy-entity loading mechanism.
If you need the property to always yield an instance of the concrete type when it can differ from the mapped one, you can disable the lazy loading, as you have reported.
Another possible way should be to map the `one-to-one` with `lazy="no-proxy"`, which will cause it to be handled somewhat like a lazy non-association property, causing the holding entity to be proxified in a lazy-property proxy.
(NHibernate handles two kind of proxies: entity proxies, for loading lazily a whole entity, and lazy-property proxies, for loading lazy properties of the entity they proxify.)

**Comment by fubar-coder** [comment]
Ok, thanks for the explanation. It seems that NHibernate used a proxy for a one-to-one to an abstract base class.

This is my configuration:

```xml
<?xml version="1.0" encoding="utf-8"?>
<hibernate-mapping xmlns="urn:nhibernate-mapping-2.2">
  <class name="TestClass" table="TestsTable">
    <id name="Id" generator="guid.comb" />
    <bag name="Things" lazy="extra" cascade="all-delete-orphan" inverse="true">
      <key column="TestId" not-null="true" />
      <one-to-many class="TestThingClass" />
    </bag>
  </class>

  <class name="TestThingClass" table="TestThingsTable">
    <id name="Id" column="ThingId">
      <generator class="foreign">
        <param name="property">Test</param>
      </generator>
    </id>
    <many-to-one name="Test" column="TestId" not-null="true" />
    <one-to-one name="Thing" cascade="all-delete-orphan" constrained="true" lazy="false" />
  </class>

  <class name="ThingClass" table="ThingsTable" discriminator-value="null" abstract="true">
    <id name="Id" generator="guid.comb" />
    <discriminator type="int" column="Type" not-null="true" />
    <property name="BaseNumber" not-null="true" />

    <subclass name="ThisThingsClass" discriminator-value="1">
      <property name="ThisNumber" not-null="true" />
    </subclass>
    <subclass name="ThatThingsClass" discriminator-value="2">
      <property name="ThatNumber" not-null="true" />
    </subclass>
  </class>
    
</hibernate-mapping>
```

And the classes:

```cs
public class TestClass
{
    public virtual Guid Id { get; set; }
    public virtual ICollection<TestThingClass> Things { get; set; }
}

public class TestThingClass
{
    public virtual Guid Id { get; set; }
    public virtual TestClass Test { get; set; }
    public virtual ThingClass Thing { get; set; }
}

public abstract class ThingClass
{
    public virtual Guid Id { get; set; }
    public virtual int Type { get; set; }
    public virtual int BaseNumber { get; set; }
}

public class ThisThingClass
{
    public virtual int ThisNumber { get; set; }
}

public class ThatThingClass
{
    public virtual int ThatNumber { get; set; }
}
```

I'll try to create a unit test and hopefully it was just a misconfiguration on my side.

**Comment by fredericDelaporte** [comment]
> It seems that NHibernate used a proxy for a one-to-one to an abstract base class.

Yes it does, and this is expected as long as the constrained one-to-one is mapped as the base class. That is the case in your example mapping, so you can expect to have a proxy of the abstract class returned by the `Thing` property. (Unless this thing was already loaded with its concrete type in the session.)
