### ISSUE TITLE
Class with string key is retrieved with wrong case from the db

### ISSUE THREAD

**Issue by ador-mg** [nhibernate/nhibernate-core#1865]
I have an entity with an assigned string key. 
When using Session.Get to retrieve it from the database, with a different case that it is saved,
then the object is returned but the key value is the one I supplied and not the one that is in the database (in terms of case).
The database is MSSQL and has a CI collation.

Here is the test case:

```
using (var session = OpenSession())
using (var transaction = session.BeginTransaction())
{
	User user = new User();
	user.UserName = @"Domain\User";
	session.Save(user);
	Role role = new Role();
	role.RoleName = "Admins";
	session.Save(role);
	transaction.Commit();
}

using (var session = OpenSession())
using (var transaction = session.BeginTransaction())
{
    User user = (User) session.Load(typeof(User), @"Domain\User");
    Role role = (Role) session.Load(typeof(Role), "Admins");
    UserToRole userToRole
        = new UserToRole
        {
            User = user,
            Role = role
        };
    session.Save(userToRole);
    transaction.Commit();
}

using (ISession session = OpenSession())
{
    User user = session.Get<User>(@"domain\user");
    Assert.AreEqual(@"Domain\User", user.UserName);
    Assert.AreEqual(1, user.UserToRoles.Count);              
}
```

Both of the last two assertions fail.

However, if I use something like: 

```
using (ISession session = OpenSession())
{
    User user = session.Query<User>()
        .WithOptions(options => options.SetCacheable(true))
        .SingleOrDefault(a => a.UserName == @"domain\user");
    Assert.AreEqual(@"Domain\User", user.UserName);
    Assert.AreEqual(1, user.UserToRoles.Count);
}
```
the assertions succeed. 

My question is: why does NH replace the retrieved value with the one supplied in the _session.Get_ method and not when using the query?
imo the _session.Get_ method should also fetch the entity just like the _session.Query_ does, without changing the key.

P.S. I have looked at [NH732](https://nhibernate.jira.com/browse/NH-732) but mine is a different case. The data (PK and FKs) in the database are consistent. No problem there. The only issue is when a key with an incorrect case is supplied to the Get method.

**Comment by fredericDelaporte** [comment]
When you use `Get` or `Load`, NHibernate assumes you provide the exact identifier and do not re-read it from the database. This is by design. If the provided id is potentially not identical to the one matched in database, and you need the entity to be loaded with the exact id in the database, you have to use a query.
 
When a query is used, even if it queries by id, NHibernate has no previous knowledge of which value the id is supposed to have, and so it reads it from the database.

In some cases, the id case mismatch could cause bugs in some other NHibernate features like lazy-loading of collections, due to the `StringType` equality being case sensitive.
#1833 will allow to adjust case sensitivity of `StringType` comparisons for solving those bugs.

Read more on this in #1828.

**Comment by ador-mg** [comment]
Great! Thank you Frederic.
