### ISSUE TITLE
NHibernate v4.1.2 reports as the incorrect version, with no binding redirect added either (see screenshot within)

### ISSUE THREAD

**Issue by Jestar342** [nhibernate/nhibernate-core#1877]
I'm well aware this is an old version, I am only posting because a) we haven't been able to migrate to v5 yet and b) I want to avoid this problem in the future updates c) if anyone else finds this I have a workaround.

Screenshot of "issue": https://imgur.com/TWR0f5F

This actually causes `FileLoadException` when attempting to run: `System.IO.FileLoadException : Could not load file or assembly 'NHibernate, Version=4.1.2.4000, Culture=neutral, PublicKeyToken=aa95f207798dfdb4' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

The workaround is to redirect 4.1.2 to 4.1.0:

      <dependentAssembly>
        <assemblyIdentity name="NHibernate" publicKeyToken="aa95f207798dfdb4" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.2.4000" newVersion="4.1.0.4000" />
      </dependentAssembly>

HTH

**Comment by oskarb** [comment]
Not quite sure what's going on there. The assembly version (as opposed to
the file version) should be 4.1.0.4000 for all 4.1.x releases. Why is VS
looking for assembly version 4.1.2.4000?

Den tors 18 okt. 2018 kl 10:52 skrev Jestar342 <notifications@github.com>:

**Comment by Jestar342** [comment]
I honestly couldn't tell you. I'm only using nuget packages for nhibernate - i.e. no manuallly added references, yet until I added a redirect for 4.1.2 -> 4.1.0 it failed to load (as per the message).

**Comment by fredericDelaporte** [comment]
I have no issues using NH 4.1.2 in a test project. Without detailed steps for reproducing the issue on a clean desktop, I do not think we will find out what is wrong.

I do not think the trouble lies on NHibernate side by the way. Its assembly version is (and has to be) 4.1.0.4000, since it is a patch of 4.1, binary compatible with it. Only its file version has to change, and is actually 4.1.2.4000, which is what it should be.

Are you sure your application has not some custom loading logic, which would attempt to load NHibernate with a wrong assembly version in its fully qualified name?

**Comment by Jestar342** [comment]
No, nothing out of the ordinary. Installed with nuget (across several projects within the solution) and no extraneous loading logic.

**Comment by oskarb** [comment]
I just tried 4.1.2 from nuget in a new test project also. Works fine. No
binding redirect required.

The correct reference is automatically produced in the csproj:
    <Reference Include="NHibernate, Version=4.1.0.4000, Culture=neutral,
PublicKeyToken=aa95f207798dfdb4, processorArchitecture=MSIL">

<HintPath>..\packages\NHibernate.4.1.2.4000\lib\net40\NHibernate.dll</HintPath>
    </Reference>

Are you using any other library that references NHibernate? Might that
library somehow have been compiled using a broken (non-official) build of
NHibernate with the wrong assembly version?

I think you need to break it down - start with an empty project and the
NHibernate reference, then add any additional libraries one at a time. I
think you need to actually execute a call to any such library to trigger
the load.

Look for leftover obsolete assemblies in build folders that may be remnants
from earlier stages but are not updated because the project has been moved
or renamed.

/Oskar



Den tors 18 okt. 2018 kl 18:50 skrev Jestar342 <notifications@github.com>:

**Comment by hazzik** [comment]
Could not reproduce.
