### ISSUE TITLE
DML insert fails when a filter is enabled

### ISSUE THREAD

**Issue by gokhanabatay** [nhibernate/nhibernate-core#1921]
When a HQL `Insert` is attempted from a selected entity having a filter enabled, an invalid query is generated.

Consider following pseudo HQL code: `insert into Target (...) select ... from Source`. If `Source` has a filter enabled, the filter fragment is appended to the query, but its parameters are neither processed nor have their values supplied.

`update` and `delete` do not fail with filters: they completely ignore them.

Initial report:
---

Insert select dml style statement with filter data is not bind to sql parameters ORA-01008 : Not all variables bound

collectionRole is passed null
![image](https://user-images.githubusercontent.com/9988911/49520807-23e85d80-f8b5-11e8-9be7-e4178a341b50.png)

So is filter enabled parameter setted to false by doing collectionRole != null, but enabled filter is not empty its filled with my filter.
![image](https://user-images.githubusercontent.com/9988911/49520926-598d4680-f8b5-11e8-9132-e3eacd2a9e25.png)

It is added to where criteria but parameters is empty, and it's not added to parameter collection.
![image](https://user-images.githubusercontent.com/9988911/49521507-a0c80700-f8b6-11e8-912e-ba6697499e2b.png)

```c#
 var query = ISession.CreateQuery(
                $@"INSERT INTO {typeof(Session)}(MbrId, UserCode, OpenDate, IsClosed, ExpireDateTime,
                RemoteIpAddress, RemotePort, LocalIpAddress, LocalPort, Claims)
                SELECT E.MbrId, E.UserCode, E.OpenDate, E.IsClosed, E.ExpireDateTime,
                E.RemoteIpAddress, E.RemotePort, E.LocalIpAddress, E.LocalPort, E.Claims from {typeof(Session)} AS E");

            processedCount = query.ExecuteUpdate();
```

**Comment by fredericDelaporte** [comment]
Personally, I will not investigate any more any report from you without a proper test case. The way many of your issues are written, investigating them generally require a lot of time for trying to elaborate a test allowing to reproduce them.

Also, you may consider reading this:
http://nhibernate.info/doc/project/the-best-way-to-get-nhibernate-community-support-submit-precise-description-of-the-problem.html

**Comment by gokhanabatay** [comment]
I am working on test case I will post today @fredericDelaporte

**Comment by gokhanabatay** [comment]
@fredericDelaporte  I could not run your sample so, I create a small test project one entity and 6 test cases that simulate this and nullable order by caluse  please check it out.

Configuration: Postgresql, Log4net, FluentNhibernate, No Second Level Cache
Same issue happens  Postgressql too. 

https://github.com/gokhanabatay/NHibernateBugTest

**Comment by fredericDelaporte** [comment]
A cleaned-up test case has been put in #1926.

It also has tests for `update` and `delete`, in order to check them too. It appears that they do completely ignore enabled filters. So they do not fail with an exception, but filters are not supported by them.

So the current situation is that NHibernate does not support combining filters with DML statements. Filters are ignored.
But a bug in the insert case causes filters to wreck the insert. This is the bug to be fixed here.

Eventually, a distinct issue should be opened if it is wished to have filters supported by DML statements, instead of being ignored.

**Comment by maca88** [comment]
I've checked what it takes to add support for it and it seems that is quite easy, just by copying the method `Loader.ExpandDynamicFilterParameters` and use it the `BasicExecutor` the insert started working. [Here](https://github.com/maca88/nhibernate-core/commit/7e45cf196ab42b36592234c67d8c099f3990305f) is a quick commit that demonstrate it. Maybe we could fix it by supporting it or leave it for a next release.

**Comment by fredericDelaporte** [comment]
Why not supporting it, if that is indeed easy also for update and delete. But better do another PR, maybe taking just my tests. It will still be a possible breaking change, but I think it is an acceptable one. I was just not considering investigating how to support filters with DML.

The insert case is maybe easy, since filters are handled in a select clause, which is already supported by HQL. But for update and delete, maybe more work will be required. And supporting it only for insert and not for update and delete will be a bad inconsistency in my opinion.

**Comment by maca88** [comment]
I agree. I will check also the update and delete statements and see what has to be done.
