### ISSUE TITLE
StackExchangeRedisCache with PreferMultipleGet = true calls GetMany multiple times

### ISSUE THREAD

**Issue by gokhanabatay** [nhibernate/nhibernate-core#2127]
Hi @fredericDelaporte,  @maca88 , @hazzik 
I try to use NHibernate.Caches.StackExchangeRedis with PreferMultipleGet = true option but; it calls GetMany over an over record count.

> In ReadWriteCache result[i] = null;  makes cache GetMany call over an over why is that we already get the whole data just one call?

It has the same issue with GetManyAsync
Also is it really need to "lock" with Get operation, we already check timestamp cache? 
May be NonstrictReadWriteCache is the answer for less locking.

```c#
public object[] GetMany(CacheKey[] keys, long timestamp)
{
	if (log.IsDebugEnabled())
	{
		log.Debug("Cache lookup: {0}", string.Join(",", keys.AsEnumerable()));
	}
	var result = new object[keys.Length];
	lock (_lockObject)
	{
		var lockables = _cache.GetMany(keys.Select(o => (object) o).ToArray());
		for (var i = 0; i < lockables.Length; i++)
		{
			var lockable = (ILockable) lockables[i];
			var gettable = lockable != null && lockable.IsGettable(timestamp);

			if (gettable)
			{
				if (log.IsDebugEnabled())
				{
					log.Debug("Cache hit: {0}", keys[i]);
				}
				result[i] = ((CachedItem) lockable).Value;
			}

			if (log.IsDebugEnabled())
			{
				log.Debug(lockable == null ? "Cache miss: {0}" : "Cached item was locked: {0}", keys[i]);
			}

			result[i] = null; 
		}
	}
	return result;
}
```

> If PreferMultipleGet = true then StandartQueryCache Get operation calls GetMany when batching enabled. Then gets table updatetimestampscache from cache.
This code calls cache server again and again. With batching it could be done with single call?

```c#
public IList Get(QueryKey key, ICacheAssembler[] returnTypes, bool isNaturalKeyLookup, ISet<string> spaces, ISessionImplementor session)
{
	if (Log.IsDebugEnabled())
		Log.Debug("checking cached query results in region: '{0}'; {1}", _regionName, key);

	var cacheable = (IList) Cache.Get(key);
	if (cacheable == null)
	{
		Log.Debug("query results were not found in cache: {0}", key);
		return null;
	}

	var timestamp = (long) cacheable[0];

	if (Log.IsDebugEnabled())
		Log.Debug("Checking query spaces for up-to-dateness [{0}]", StringHelper.CollectionToString(spaces));

	if (!isNaturalKeyLookup && !IsUpToDate(spaces, timestamp))
	{
		Log.Debug("cached query results were not up to date for: {0}", key);
		return null;
	}

	return GetResultFromCacheable(key, returnTypes, isNaturalKeyLookup, session, cacheable);
}
```

**Comment by hazzik** [comment]
It seems that else is missing.

**Comment by maca88** [comment]
> it calls GetMany over an over record count.

When a cache miss happens for an entity there will be 2 more `GetMany` calls when using `read-write` cache, check tests in #2132 for more details. Due to the discovered bug which produces a cache miss for entities that are stored in cache, `GetMany` was called multiple times also for them.

> Also is it really need to "lock" with Get operation, we already check timestamp cache?

The lock is there in order to block readers from reading while a write operation is in progress. Here we should switch to [ReaderWriterLockSlim](https://docs.microsoft.com/en-us/dotnet/api/system.threading.readerwriterlockslim) so that the lock happens only when a write operation is triggered, which is what Hibernate [AbstractReadWriteAccess](https://github.com/hibernate/hibernate-orm/blob/e5dc635a52362f69b69acb8d5b166b69b165dbbd/hibernate-core/src/main/java/org/hibernate/cache/spi/support/AbstractReadWriteAccess.java#L33) does. Unfortunately, there is no async counterpart for it and we would need to implement one like [here](https://devblogs.microsoft.com/pfxteam/building-async-coordination-primitives-part-7-asyncreaderwriterlock/).

> This code calls cache server again and again. With batching it could be done with single call?

This is a side effect of the discovered bug.
