### ISSUE TITLE
AdoTransaction memory leak (5.2.5)

### ISSUE THREAD

**Issue by Logos27** [nhibernate/nhibernate-core#2144]
I'm investigation memory leak in my project. I found one of memory leak reasons inside NHibernate assembly. AdoTransaction objects created in NHibernate.AdoNet.AbstractBatcher.Prepare() via accessing property NHibernate.AdoNet.ConnectionManager.Transaction are not disposing.

![image](https://user-images.githubusercontent.com/49984815/56737591-726a9b80-6773-11e9-85f1-5eb90e451618.png)

So i tried to fix it.

First change in NHibernate\Transaction\AdoTransaction.cs
![image](https://user-images.githubusercontent.com/49984815/56736624-5108b000-6771-11e9-8745-af5bc412a02f.png)

Second change in NHibernate\AdoNet\ConnectionManager.cs 
![image](https://user-images.githubusercontent.com/49984815/56736880-f0c63e00-6771-11e9-949a-13ee2520d53a.png)

I'm not sure that thouse changes are correct but now all work fine. Can you check it?

**Comment by bahusoid** [comment]
> AdoTransaction objects created in NHibernate.AdoNet.AbstractBatcher.Prepare()

It seems this place shouldn't create transaction if it doesn't exists.

**Comment by Logos27** [comment]
Prepare() calls getter of Transaction. Transaction property creates AdoTransaction.

```
protected void Prepare(DbCommand cmd)
		{
			try
			{
				var sessionConnection = _connectionManager.GetConnection();

				if (cmd.Connection != null)
				{
					// make sure the commands connection is the same as the Sessions connection
					// these can be different when the session is disconnected and then reconnected
					if (cmd.Connection != sessionConnection)
					{
						cmd.Connection = sessionConnection;
					}
				}
				else
				{
					cmd.Connection = sessionConnection;
				}

				_connectionManager.**Transaction**.Enlist(cmd);
				Driver.PrepareCommand(cmd);
			}
			catch (InvalidOperationException ioe)
			{
				throw new ADOException("While preparing " + cmd.CommandText + " an error occurred", ioe);
			}
		}

```
```
public ITransaction Transaction
		{
			get
			{
				if (_transaction == null)
				{
					_transaction = Factory.TransactionFactory.**CreateTransaction**(Session);
				}
				return _transaction;
			}
		}
```

**Comment by hazzik** [comment]
>It seems this place shouldn't create transaction if it doesn't exists.

It creates "AdoTransaction" (a wrapper), but not actual DbTransaction, however, this depends on implementation.

**Comment by Logos27** [comment]
AdoTransaction is a disposable object and must be disposed. I understand that AdoTransaction is a wrapper but it doesn't matter in this situation. If GC can't finalize disposable objects, they stay in memory and become reason of memory leak.

**Comment by fredericDelaporte** [comment]
Your proposal looks adequate to me. May you issue a PR please?

**Comment by fredericDelaporte** [comment]
Well, to ensure we do not have a double call to after transaction in case a rollback or commit fails, better also adjust `AdoTransaction.AfterTransactionCompletion` for setting `begun` to false before calling `AfterTransaction` on the connection manager.

**Comment by bahusoid** [comment]
This `Dispose` call looks kinda fishy to me -  doesn't look like proper usage for disposable pattern. And I'm not sure I understand the source of the leak.
Is it the case when user calls `session.BeginTransaction()` and doesn't dispose it yourself? Or is it some case when transaction is started implicilty? As if batcher (`NHibernate.AdoNet.AbstractBatcher.Prepare()`) creates only transactoin wrapper it shouldn't be the source of the memory leak. Or am I wrong?

**Comment by fredericDelaporte** [comment]
It is not fishy from my viewpoint.

The NHibernate `AdoTransaction` is lazily created by the connection manager by a simple read of its `Transaction` property. It is not done by a public method explicitly asking for such a creation, so that is the connection manager responsibility to dispose of it when it releases its reference on it. Currently, it already disposes it, but only in its own dispose. But during its life-cycle, the connection manger may create many transactions, and so it will release only the last one it has created.
The place pinpointed by Logos27 is the place where the connection manager should handle the disposal of the other `AdoTransaction` it has created.

Yes, the user should also dispose the transaction it gets from the session with `BeginTransaction`, where he explicitly asks for a new transaction. But that may not cover all the cases, due to the current connection manager pattern.

**Comment by Logos27** [comment]
> Well, to ensure we do not have a double call to after transaction in case a rollback or commit fails, better also adjust `AdoTransaction.AfterTransactionCompletion` for setting `begun` to false before calling `AfterTransaction` on the connection manager.

Yes, this is a way to avoid my breakage of dispose pattern.

> Is it the case when user calls `session.BeginTransaction()` and doesn't dispose it yourself?

It is the case when user doesn't create explicit transaction. So ConnectionManager creates implicit transaction inside ConnectionManager.Transaction property. If ConnectionManager created transaction then ConnectionManager must dispose transaction. Besides, user doesn't have access to the implicit transaction because it clears in line ConnectionManager.cs:284 _transaction = null;

> As if batcher (`NHibernate.AdoNet.AbstractBatcher.Prepare()`) creates only transactoin wrapper it shouldn't be the source of the memory leak. Or am I wrong?

Any disposable object that is not disposed and is not finalized is a reason of memory leak. Object of AdoTransaction class is a disposable object.
In my case I have a lot of objects in finalization queue and because of some reason thay are not finalized. May be GC is very busy. :) So I want to avoid finalization by calling Dispose() { ... GC.SuppressFinalize(); ... }

fredericDelaporte, I totally agree with your last post

**Comment by bahusoid** [comment]
Disposable objects should not be created implicitly and all tricks to make sure that such objects are disposed I consider hacky. So IMHO proper fix should remove implicit `AdoTransaction` creation. But maybe it can't be done without breaking changes so your suggested fix should still be applied.

>So I want to avoid finalization by calling Dispose() { ... GC.SuppressFinalize(); ... }

I'm not quite sure what your image shows with 500k objects (finalization queue?) - but it's better to avoid creation of such pile of objects instead of calling `GC.SuppressFinalize` for all of them.
