### ISSUE TITLE
Using DependentTransaction fails

### ISSUE THREAD

**Issue by guoleilove33** [nhibernate/nhibernate-core#2172]
When I use `Transaction.Current.DependentClone(DependentCloneOption.RollbackIfNotComplete)`, Nhibernate went wrong. The error message is `HibernateException: Synchronization timeout for transaction completion. Either raise {Cfg.Environment.SystemTransactionCompletionLockTimeout}, or this may be a bug in NHibernate.`. This error may occur in NHibernate 5.x.x
Here is the code:
```c#
    public class TestNHibernate
    {
        public static void Main(string[] arg)
        {
            new TestNHibernate().Do1();
        }
        public virtual void Do1()
        {
            Transaction.Current = new CommittableTransaction();
            var current = Transaction.Current;
            Do2();
            (current as CommittableTransaction)?.Commit();
        }
        public virtual void Do2()
        {
            var current1 = Transaction.Current;
            Transaction.Current = Transaction.Current.DependentClone(DependentCloneOption.RollbackIfNotComplete);
            var builtSessionFactory =
                Fluently.Configure()
                    .Database(
                        MsSqlConfiguration.MsSql2012.ConnectionString(
                            @"Server=localhost;Database=test;user=sa;password=123;Trusted_Connection=True;"))
                    .Mappings(m => m.FluentMappings.Add<PM>())
                    .BuildSessionFactory();
            var session = builtSessionFactory.OpenSession();
            session.Save(new Person { });
            (Transaction.Current as DependentTransaction).Complete();
            Transaction.Current.Dispose();
            Transaction.Current = current1;
        }
        public class Person
        {
            public virtual int Id { get; set; }
            public virtual string Name { get; set; }
        }
        public class PM : ClassMap<Person>
        {
            public PM()
            {
                Id(person => person.Id);
                Map(u => u.Name);
            }
        }
    }
```

**Comment by fredericDelaporte** [comment]
There is some ongoing work to support dependent transaction in NH 5.x, currently targeted to 5.2.x but which may be back-ported down to 5.0.x. See #2197.

Since this regression is two years old and is only reported now, it seems using dependent transaction is not very common place. And we were indeed not having any test on them. Just fixing the test case you provide here may not be enough to fix it entirely.

To avoid a multi-releases fix process, may you please test the binaries from the PR builds with your real case application? In the PR's builds list, you can go the details of "NHibernate (Release Package)" build, login into TeamCity (anonymous logon available), and retrieves build artifacts (including a NuGet package) from the artifacts tab.

**Comment by guoleilove33** [comment]
Ok ,thanks very much
