### ISSUE TITLE
ISessionFactory.Close should short-circuit when already closed.

### ISSUE THREAD

**Issue by deAtog** [nhibernate/nhibernate-core#2193]
`SessionFactoryImpl.Close` currently allows the body of the function to be run multiple times as it does not check if it is closed prior to proceeding. This should be changed so that `Close` when called from `Dispose` does nothing when `Close` has been called by the application.

**Comment by deAtog** [comment]
Upon further review, it seems that calling `SessionFactoryImpl.Close` from the finalizer is not advisable because the garbage collector does not guarantee the order in which finalizers are called. Thus manged objects may already have been garbage collected. I.E. associated `ICacheProvider` and `CacheBase` instances may have already been garbage collected. I still support the idea of implementing `IDisposable`... but maybe `Configuration.BuildSessionFactory` should return a `SessionFactoryImpl` rather than an ISessionFactory. Then applications can either call `Close` or `Dispose` to free the managed resources?

Regardless of what is decided here, users should be advised to close or dispose `SessionFactoryImpl` instances.

**Comment by fredericDelaporte** [comment]
Implementing the finalizer pattern is not recommended unless the class directly holds references on un-managed resources. Because anyway, when called from finalizer, the dispose should not attempt to dispose any managed resource, which may be already freed (as your second message states). It should dispose only un-managed ones.

This is why there are no point in implementing a finalizer unless the class directly holds un-managed resources.
(Moreover, the class being sealed, it may not be extended into another class which may have the need for the `protected virtual void Dispose(bool disposing)` recommended in the Microsoft link.)

> It should also be worth noting here that `SessionFactoryImpl.Close` currently allows the body of the function to be run multiple times as it does not check if it is closed prior to proceeding.

You are right, and this could be a trouble. I think a short-circuit on `isClosed` should be added at the start of the close method.

> Additionally, all `ICacheProvider`'s should probably contain a finalizer that calls `ICacheProvider.Stop` to ensure managed and unmanaged resources are in a consistent state.

No, as already explained by your later message and my answer here.

> _Note:_ An application cannot call `ISessionFactory.Dispose` as `Dispose` is not part of that interface.

Are you using a very old version, prior to 1.2? This is no more the case since November 2006, see [here](https://nhibernate.jira.com/browse/NH-383). `ISessionFactory` extends `IDisposable` since long. So users can and should call dispose on `ISessionFactory`, since it is disposable.

>Regardless of what is decided here, users should be advised to close or dispose `SessionFactoryImpl` instances.

No need for this, since `ISessionFactory` is already disposable. Users should know they have to dispose it.

So, there is one point to address, the `Close` re-entry case. May you edit your first comment to put it more pro-eminently? (You can drop the other parts entirely if you feel like it, I would then likely drop them from my own message.)

**Comment by scott-korin** [comment]
I was looking into contributing and saw this listed as a "good first issue", but I also see a fix for this was already merged.
Why is this still open?

**Comment by fredericDelaporte** [comment]
It should have been closed.
