### ISSUE TITLE
Performance issues when accessing raw SQLite inside of NHibernate

### ISSUE THREAD

**Issue by MidasLamb** [nhibernate/nhibernate-core#2262]
To be able to do some SQLite specific queries, such as INSERT ... ON CONFLICT, I access the SQLite connection directly. 
There seems to be a major performance hit when doing this inside of a transaction from NHibernate (I use reflection to get the transaction to be able to include my command in it).

To isolate this I have an insert which mimics NHibernate, so no special ON CONFLICT or anything.
I also created the same insert in separate C# program which does not use any NHibernate and also accesses SQLite directly.

The timings are as follows:
*  NHibernate Session.Insert() : 0.6539 ms
* Raw SQLite inside NHibernate: 1.45272 ms (this timing is from only command.ExecuteNonQuery(), nothing from setup or parameter binding is timed here)
* Raw SQLite no NHibernate:  0.166248 ms (timing here includes parameter binding and an additional SELECT query)

The connection string used in both applications is the same.
The code from the last two is practically the same.

**Comment by hazzik** [comment]
Not even sure what you’re asking. You did not provide mapping, tables, sql generated. Nothing.

Also not sure if this problem is related to NHibernate in any how because of this:

> I use reflection to get the transaction to be able to include my command in it

NHibernate has an API to write native queries without frictions.

**Comment by MidasLamb** [comment]
We noticed that skipping NHibernate for certain queries gave a performance gain. So we tried some other queries as well, some that were critical, but we noticed that some queries run significantly faster without a NHibernate environment around then with one, even though the queries themself don't interact with nhibernate. I was wondering what the cause might be of this? Or how to subvert this behaviour without completely removing NHibernate from the codebase.

**Comment by fredericDelaporte** [comment]
I do not get it either, and I also doubt NHibernate is actually related to your perf trouble. It may be your own code / seemingly complicated way of performing native queries with NHibernate, or something else, like testing the "NHibernate" case inside an actual application implying a lot of additional code which may interfere, compared to your separated "raw" program made only for your separate bench. Without a proper test case, there is a no way to tell.

As explained by Hazzik, there are no need to use reflection for performing native SQL queries within a NHibernate transaction. Just use the right API on the session, `ISession.CreateSQLQuery`, then `ExecuteUpdate` on it if you have no results to get.

If you actually found something related to NHibernate, please supply proper evidence, like a test case allowing to repro the perf discrepancy, see [contributing](https://github.com/nhibernate/nhibernate-core/blob/master/CONTRIBUTING.md). Nothing prevents you using directly a native connection in such test cases in order to bench your many cases, like [here](https://github.com/nhibernate/nhibernate-core/blob/f1c88c21d9b8ad9160e395b9e96444a3ec33b4c9/src/NHibernate.Test/NHSpecificTest/NH2420/Fixture.cs#L51). (This example of getting a native connection unbound to a session inside a NHibernate test case can be simplified to [this](https://github.com/nhibernate/nhibernate-core/blob/9aebf9db3e3cd7f7280644f0d9c84cfb9d505fc2/src/NHibernate.Test/NHSpecificTest/NH2420/Fixture.cs#L65).)

**Comment by MidasLamb** [comment]
@hazzik, @fredericDelaporte, i created a repo which reproduces my issue: https://github.com/MidasLamb/NHibernatePerformance.

The results from that program (which averages performance over 10000 actions), are as follows for me: 
![image](https://user-images.githubusercontent.com/14802865/68069289-76006000-fd5e-11e9-84e7-afc29f93b91f.png)

The red underlined are of interest here. You can see that while the sqlite i'm executing is the same, a previous action inside the NHibernate framework (the insert) has an effect on the performance of said sqlite.

**Comment by fredericDelaporte** [comment]
Performing entity reads is a lot heavier than just reading one column from a date reader. Sure your measurement does not include that part, but it can still affect the performance of the measured code, because an entity read implies a lot more memory operations, which may cause more garbage collections to occurs during the bench.

I do not think you will find anyone interested in investing time for checking if there is a real issue in NHibernate from your case.
