### ISSUE TITLE
The column 'column_name' has already been added in this SQL builder

### ISSUE THREAD

**Issue by MarcinSasin** [nhibernate/nhibernate-core#2268]
I know I should post on nhusers group and I did. No response so far so I am posting here. Hopefully someone will be able to help me.

I have a problem with a duplicate column as described in below issue: 
https://github.com/nhibernate/nhibernate-core/issues/2001#issue-406115169

We have already updated references as read only but we also use **joined-subclass**. The problem is there is no insert property to be set as false for KEY property of joined-subclass. So we still get the error: 
NHibernate.MappingException: 'Unable to build the insert statement for class 'abc'; a failure occured when adding the Id of the class.
The column 'column_name' has already been added in this SQL builder

It worked fine before migration to NH 5.2.3, Appreciate any idea how to handle this ?

_Originally posted by @MarcinSasin in https://github.com/nhibernate/nhibernate-core/issues/2001#issuecomment-550509730_

**Comment by fredericDelaporte** [comment]
You may have got no answer due to lack of information. Please provide example mappings reproducing the trouble you have when you ask for help.
Are you mapping the joined-subclass to the same table? If yes, the mapping should be rewritten to use `subclass` instead. See [here](https://nhibernate.info/doc/nhibernate-reference/inheritance.html).
