### ISSUE TITLE
Wrong Discriminator placement causes XML validation error

### ISSUE THREAD

**Issue by Simulacrux** [nhibernate/nhibernate-core#2279]
Hi everyone,

I currently tried the Discriminator feature  for storing several sub classes in one table.
After starting with the feature and placing the discriminator tag in my mappigns, I discovered a problem. If you are not placing the discriminator tag right after the id tag, the runtime is providing me with a error: 
`MappingException: XML validation error: The element 'class' in namespace 'urn:nhibernate-mapping-2.2' has invalid child element 'discriminator' in namespace 'urn:nhibernate-mapping-2.2'.`

From the error I'm started struggling around. First I thought, something with my discriminator was wrong, so I switched around the type and several other stuff but nothing seems to work. So I started googleing around and after some time I found a blog post, which put me in the right direction. That it is a "must" to place discriminator right below the id tag.

If this "restriction" is correct in the validation schema, I think it would be very helpful, if it would be  mentioned in the official documentation. Right now under 5.1.7 in [https://nhibernate.info/doc/nhibernate-reference/mapping.html](https://nhibernate.info/doc/nhibernate-reference/mapping.html#mapping-declaration-discriminator) nothing to this restriction is stated and so I was more or less lost for the right google search to give me a clue after trying around with no luck. 

Cheers
Simulacruxx

**Comment by deAtog** [comment]
Generally speaking when working with XML, you should provide the XML Schema Definition (XSD) to your editor so that it knows what the valid syntax is. According to the [NHibernate Mapping XSD](https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate/nhibernate-mapping.xsd), the [class definition](https://github.com/nhibernate/nhibernate-core/blob/46cf6e51b06f0bfdc845ab095f7f7f3ce1f89981/src/NHibernate/nhibernate-mapping.xsd#L127) has a `sequence` of elements under it. A `sequence` requires that the items appear in the order listed in the XSD. The online documentation is a supplement to the XSD. When in doubt, consult the XSD.

**Comment by fredericDelaporte** [comment]
The usage is detailed in the [Inheritance Mapping chapter](https://nhibernate.info/doc/nhibernate-reference/inheritance.html#inheritance-tableperclass). The ordering constraint is not explicitly stated, but that is the same for most elements. As explained by deAtog, and as stated by the |documentation][https://nhibernate.info/doc/nhibernate-reference/mapping.html#mapping-declaration-xmlns), you should enable schema validation for your mappings. With an up-to-date VS, you can do this also through the XML > Schemas menu when you have a mapping file opened.
