### ISSUE TITLE
SQL Server - DateTime columns always queried with DateTime2 parameters

### ISSUE THREAD

**Issue by joel100** [nhibernate/nhibernate-core#2289]
We are in the process of upgrading from Nhibernate 4 to 5.2.6. We're running into a problem where all query parameters for datatime columns appear to be being marked as datetime2

Because of this some queries are not returning results that should return a result. 

This is simplified example of a query generated for a partitioned table. This doesn't return a result despite the the value in the InsertedAt = '2019-12-17 23:16:51.753'

```
exec sp_executesql N'SELECT this_.InsertedAt as insertedat1_45_0_, this_.Id as id2_45_0_, FROM dbo.TableName this_ WHERE this_.InsertedAt = @p0 and this_.Id = @p1',N'@p0 datetime2(7),@p1 uniqueidentifier',@p0='2019-12-17 23:16:51.7530000',@p1='CE353AE0-5F64-4A4D-A93E-AB26017FA8E8'
```

InsertedAt is defined like this with FluentNhibernate
```
    CompositeId()
        .KeyProperty(x => x.InsertedAt).CustomType<DateTimeType>()
        .KeyProperty(x => x.Id);
```

in version 4 it was defined as 
```
   CompositeId()
       .KeyProperty(x => x.InsertedAt).CustomType<TimestampType>()
       .KeyProperty(x => x.Id);
```

The SQL below seems to show that there are problems with datetime2 to datetime equality comparisons 

```
DECLARE @date2 datetime2(7)
SET @date2='2019-12-17 23:16:51.7530000'
DECLARE @date datetime
SET @date = @date2
SELECT CASE WHEN @date = @date2 THEN 1 ELSE 0 END
```
SQL Server believes @date is larger than @date2

What am I missing / doing wrong here?

**Comment by hazzik** [comment]
It worth looking into [release notes for possible breaking changes](https://github.com/nhibernate/nhibernate-core/blob/master/releasenotes.txt#L861) before creating an issue:

> * SQL Server 2008+ dialects now use datetime2 instead of datetime for all date-time types, including timestamp. This can be reverted with sql_types.keep_datetime setting.

**Comment by joel100** [comment]
Helpful ... when google returns no results to a dozen searches you come to the source.

It would be helpful if this wasn't just buried in release notes but not clearly called out somewhere in the documentation with examples?

**Comment by joel100** [comment]
Thank you, after several hours of searching google I didn't find an answer to this.

**Comment by fredericDelaporte** [comment]
Google is not always the answer to everything in the universe. And cluttering the documentation about every changes in the history of NHibernate, especially about obsolete things (using `datetime` instead of `datetime2` with SQL-Server), would not be a very practical solution.
But anyway, this parameter is documented, see the [documentation](https://nhibernate.info/doc/nhibernate-reference/session-configuration.html#configuration-optional).
IMO, it is still easier to review the release notes when upgrading, rather than waiting for bugs then googling and hoping for a relevant result toward some documentation.
