### ISSUE TITLE
Invalid update on immutable versioned entity with mutable inverse collection

### ISSUE THREAD

**Issue by rezajp** [nhibernate/nhibernate-core#2340]
I have recently upgraded from NHibernate 4.xx to 5.2 and I am having an issue when during a transaction that I have made a few saves (inserts) and once I query, NHibernate decides that it should flush the session and when it does, it wants to update an entity even though I have not explicitly updated it (it is a new entity) and that entity is ReadOnly so it generates an update sql with no SET 
```
UPDATE [Redemption] SET  WHERE Id = ? AND Version = ?]

2020-03-26 15:59:02,909 [22] DEBUG NHibernate.Transaction.AdoTransaction - Enlist Command
2020-03-26 15:59:02,913 [22] DEBUG NHibernate.AdoNet.AbstractBatcher - ExecuteReader took 0 ms
2020-03-26 15:59:02,917 [22] DEBUG NHibernate.AdoNet.AbstractBatcher - Opened DbDataReader, open DbDataReaders: 1
2020-03-26 15:59:02,923 [22] DEBUG NHibernate.AdoNet.AbstractBatcher - Closed DbDataReader, open DbDataReaders :0
2020-03-26 15:59:02,926 [22] DEBUG NHibernate.AdoNet.AbstractBatcher - DataReader was closed after 13 ms
2020-03-26 15:59:02,929 [22] DEBUG NHibernate.AdoNet.AbstractBatcher - Closed DbCommand, open DbCommands: 0
2020-03-26 15:59:02,933 [22] DEBUG NHibernate.Persister.Entity.AbstractEntityPersister - Updating entity: [Loyalty.Services.Domain.Eurostar.Redemption#20047027]
2020-03-26 15:59:02,937 [22] DEBUG NHibernate.Persister.Entity.AbstractEntityPersister - Existing version: System.Byte[] -> New Version: System.Byte[]
2020-03-26 15:59:02,940 [22] DEBUG NHibernate.AdoNet.AbstractBatcher - Opened new DbCommand, open DbCommands: 1
2020-03-26 15:59:02,944 [22] DEBUG NHibernate.AdoNet.AbstractBatcher - Building an DbCommand object for the SqlString: UPDATE [Redemption] SET  WHERE Id = ? AND Version = ?
2020-03-26 15:59:02,947 [22] DEBUG NHibernate.Persister.Entity.AbstractEntityPersister - Dehydrating entity: [Loyalty.Services.Domain.Eurostar.Redemption#20047027]
2020-03-26 15:59:02,961 [22] DEBUG NHibernate.SQL - UPDATE [Redemption] SET  WHERE Id = @p0 AND Version = @p1;@p0 = 20047027 [Type: Int32 (0:0:0)], @p1 = 0x00000000000459B1 [Type: Binary (8000:0:0)]
2020-03-26 15:59:02,965 [22] DEBUG NHibernate.Transaction.AdoTransaction - Enlist Command
2020-03-26 15:59:02,970 [22] ERROR NHibernate.AdoNet.AbstractBatcher - Could not execute command: UPDATE [Redemption] SET  WHERE Id = @p0 AND Version = @p1
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near the keyword 'WHERE'.
```

Is this a bug or something has changed that I need to take into account?

**Comment by rezajp** [comment]
When I remove the collection (inversed) from the mapping it gets fixed!

**Comment by fredericDelaporte** [comment]
It looks like a bug but please provide more information.
We need a minimal but complete (class definition, mappings, code executed, ...) example allowing to reproduce the issue, or even better [PR directly](https://github.com/nhibernate/nhibernate-core/blob/master/CONTRIBUTING.md#creating-a-test-case-to-verify-the-issue) a test case.

**Comment by rezajp** [comment]
Thanks Frederic. Putting the code here might be difficult as the whole execution would be a lot of code. I will try doing the test case. Should I do that on master branch?

**Comment by rezajp** [comment]
I think there is already a test for this NHibernate.Test.Immutable.EntityWithMutableCollection.Inverse.VersionedEntityWithInverseOneToManyFailureExpectedTest and it is ignored!

My entity A is immutable and it has a OneToMany relationship with another immutable entity B and both of them are versioned. Entity B also has OneToMany relationship with entity C. I had to remove those OneToMany relationships (and only keep ManyToOne from the other entity) to fix the issue.

**Comment by bahusoid** [comment]
You may try as workaround make your OneToMany mappings immutable( `mutable="false"`)? Or try to disable optimistic locking for those OneToMany mappings (`optimistic-lock="false"`).

**Comment by rezajp** [comment]
Setting optimistic lock to false fixed the issue but setting onetomany mapping to immutable didn't.

**Comment by fredericDelaporte** [comment]
Good spot @bahusoid for [`optimistic-lock`](https://nhibernate.info/doc/nhibernate-reference/collections.html#collections-mapping), and good spot @rezajp for the existing test.

Those test is close to your case but does not trigger your actual trouble. Those tests fail due to false assumptions of the one having coded them. They do not emit an invalid update. In those tests, the version is generated by NHibernate, so it does not emit an empty update, it emits one with the version being set. In other words those tests have been disabled because it was believed by their coder that the update which was occurring was a bug, while it is not.

All things combined, I now think this is not a bug, but an unsupported case.

From the documentation linked above:
> `optimistic-lock` (optional - defaults to `true`): specifies that changes to the state of the collection results in increment of the owning entity's version. For one to many associations, you may want to disable this setting. 

So it is expected that NHibernate attempts to perform an update on the owning entity on collection change. (This setting is independent of the `inverse` one.) But on a non-mutable entity where the version is generated db-side, there are no column to update, so it fails.
Bottom-line: you cannot use optimistic locking on the owning entity of a collection if that entity is not mutable and the version is generated on the db side. Since it is enabled by default, you have to disable it in such case.

It could maybe be handled better by automatically not versioning collection changes on the holding entity when it is the inverse end. Something like defaulting `optimistic-lock` to `true` for non-inverse collections and to `false` for inverse ones.
(But I am not so sure about this. Sometimes, "better is enemy of good" (quite literally translated from the French way of saying it, I hope it makes sense in English); the consequences of such a change would have to be thoroughly checked.)

As for the consequences of disabling it, I wonder, what is the point of versioning a non-mutable entity with inverse collections anyway? Versioning of the non-inverse side should be enough, or am I missing something?

**Comment by rezajp** [comment]
Thanks for thorough explanation @fredericDelaporte . I am setting the optimistic lock to false for now.

**Comment by bahusoid** [comment]
> In other words those tests have been disabled because it was believed by their coder that the update which was occurring was a bug, while it is not.

By why not? To me version field here is no different with other fields - all of them should not be updated for immutable entities.
I found current behavior is at least unexpected. Is this some known design decision? To me more logical would be to ignore  `optimistic-lock` setting or make it `false` by default for read-only entity.

**Comment by fredericDelaporte** [comment]
First, that not the fact the entity is read-only or non-mutable for its own fields/properties which may be taken into account, but whether the entity is responsible or not of its collection state (`inverse` setting).
When the collection is not `inverse`, the entity is responsible for its state, so whether is is immutable or not for its fields, it is quite legitimate to do the versioning for changes in collection on its owning entity.
When the collection is `inverse`, then it seems logic to not do the versioning on the owning entity. But that also means to cause the `optimistic-lock` setting default value to be dependent on some other setting, the `inverse` one, which is not an usual pattern in NHibernate. Thus my writing in some previous comment here:

>It could maybe be handled better by automatically not versioning collection changes on the holding entity when it is the inverse end. Something like defaulting `optimistic-lock` to `true` for non-inverse collections and to `false` for inverse ones.
>(But I am not so sure about this. Sometimes, "better is enemy of good" (quite literally translated from the French way of saying it, I hope it makes sense in English); the consequences of such a change would have to be thoroughly checked.)

That is also the likely reason for the precision on the `optimistic-lock` setting documentation:

> For one to many associations, you may want to disable this setting.

Because usually, one-to-many association collections are also mapped as inverse, and the association is controlled from the other end.

**Comment by bahusoid** [comment]
> First, that not the fact the entity is read-only or non-mutable for its own fields/properties which may be taken into account, but whether the entity is responsible or not of its collection state (inverse setting)

Ok got it.

But IMHO that's involves too deep thinking which is not very user friendly :)  It's just "optimistic-lock" setting can be very easily overlooked and I believe most people didn't aware  of it. To me ideal behavior would be "if entity is readonly don't update its version unless some setting like "optimistic-lock"  is explicitly set". And inverse/non-inverse  - doesn't matter.
