### ISSUE TITLE
InvalidOperationException: This transformer is not initialized by Cached Query

### ISSUE THREAD

**Issue by chrisredburnetail** [nhibernate/nhibernate-core#3169]
Between version 5.3.10 and 5.3.11 the behaviour of cached SQL Query results changed when using AliasToBean transform. 

```csharp
ISession session;
session.CreateSQLQuery("select 'REGIONCODE' as regionCode  ")
		.AddScalar("regionCode", NHibernateUtil.String)
		.SetResultTransformer(Transformers.AliasToBean<ResultDto>())
		.SetCacheable(true)
		.List();
```

This works the first time through when caching is enabled, but when run again it fails with a "System.InvalidOperationException : This transformer is not initialized" exception.

I've created the attached Test Case which gives the exception in the second call to .List in the GetCacheableSqlQueryResults method.

In my actual code the SELECT statement involves tables and join, etc - its been simplified for this test case to not include any entities.  

[GH3169.zip](https://github.com/nhibernate/nhibernate-core/files/9657395/GH3169.zip)

**Comment by bahusoid** [comment]
So this issue was enabled by triggering correct caching in #2943. But the problem code introduced in #1489 (ping @fredericDelaporte)
The problem here is that auto discovery type queries fills part of query cache key only after query is executed:
https://github.com/nhibernate/nhibernate-core/blob/a05f6a91e1ecf9aed2f8d495d96f85941ce0a529/src/NHibernate/Loader/Custom/CustomLoader.cs#L348-L350

But when query is retrieved from cache this part is not executed - thus we have `This transformer is not initialized` (this information is present in cached cache key, but we have no access to it). 

I think I will provide a fix that skips caching for auto discovery type queries with transformers (so kind of restore behavior before #2943) as I have no better ideas right now 

P.S. Another question why it's treated as auto discovery type query? Seems all required types are supplied explicitly...

**Comment by bahusoid** [comment]
> I think I will provide a fix that skips caching for auto discovery type queries with transformers 

Or maybe don't fix it at all till proper fix is found - so it's clear that caching doesn't work for such queries...
