### ISSUE TITLE
PostgreSQL error 42803 "subquery uses ungrouped column" when using Fetch and inner select

### ISSUE THREAD

**Issue by nkreipke** [nhibernate/nhibernate-core#3435]
The following LINQ query stopped working in 5.4:

```csharp
var newestTargetEntries = s.Query<Entry>()
    .Fetch(x => x.Update)
    .GroupBy(x => x.Target)
    .Select(x => x.OrderByDescending(y => y.Update.Date).First())
    .ToList();
```

In 5.3.19, this generated the following working SQL:

```sql
select (select entry0_.Id as id1_0_ from entry entry0_, update update2_ where entry0_.update_id=update2_.Id order by update2_.date desc limit 1) as col_0_0_ from entry entry0_ group by entry0_.target
```

In 5.4.0, it would fail with PostgreSQL error 42P01 which is probably the same bug as in #3263:

```sql
select (select entry0_.Id as id1_0_ from entry entry0_ order by update1_.date desc limit 1) as col_0_0_ from entry entry0_ group by entry0_.target
 ---> Npgsql.PostgresException (0x80004005): 42P01: missing FROM-clause entry for table  »update1_«
```

Starting with 5.4.2, it instead fails with PostgreSQL error 42803:

```sql
select (select entry0_.Id as id1_0_ from entry entry0_ order by update1_.date desc limit 1) as col_0_0_ from entry entry0_ left outer join update update1_ on entry0_.update_id=update1_.Id group by entry0_.target
 ---> Npgsql.PostgresException (0x80004005): 42803: subquery uses ungrouped column »update1_.date« from outer query
```

A workaround seems to be removing the `Fetch` clause.

I've created an example project here: https://github.com/nkreipke/NH42803

**Comment by hazzik** [comment]
> A workaround seems to be removing the Fetch clause.

Why do you need `Fetch` here? It does not do anything.

**Comment by bahusoid** [comment]
So it's a missing join in subquery issue. Looks like main fetch join is incorrectly reused (most likely caused by #2494)

**Comment by fredericDelaporte** [comment]
Putting at a low priority since, as noted by Hazzik, the `Fetch` is superfluous and should be removed. If a case where the `Fetch` is actually useful exists, it would have to be re-evaluated.

(There is no need to `Fetch` associations when using a projection of the association (a `Select` returning something from said association). Fetching is useful only when the query return entities and it is wished to have some of their associations loaded altogether.

**Comment by fredericDelaporte** [comment]
Looking into this again, I now consider the `Fetch` as invalid in this query. `Fetch` instructs to return in the select all the data of the fetched association. That is incompatible with the later `GroupBy` which does not include the association data in its grouping clause. Due to the Fetch being unneeded in this query and somewhat "overridden" by the later projection (LINQ Select), in most case it does not cause a failure although being invalid.

So, a fix of some unrelated issue has increased the number of cases where this invalid query fail. I do not think it is worth finding a fix for allowing an invalid query to work again.
